# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0/24 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #- uses: lowlighter/metrics@latest
      - uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-profile.svg

          # Options
          user: alnyz
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          repositories_forks: yes
          config_timezone: Asia/Jakarta
          # plugin_achievements: yes
          # plugin_achievements_display: compact
          # plugin_achievements_limit: 5
          # plugin_achievements_secrets: yes
          # plugin_achievements_threshold: B
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage #, lines
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
